---
title: "Untitled"
author: "Brad Price, Ph.D."
date: "9/18/2024"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Car Seats Example

We've been asked to analyze sales data for Carseats, we want to understand the drivers of sales and specificlly how area variables (US, Urban) impact sales.   

```{r}
library(ISLR)
help(Carseats)
head(Carseats)
summary(Carseats)

m1<-lm(Sales~CompPrice+Income+Advertising+Population+Price+Age+Urban+US,data=Carseats)
par(mfrow=c(2,2))
plot(m1)
summary(m1)
```

$$
Sales=7.20+0.094*CompPrice+0.013*Income+0.13*Advertising-0.0001*Population-0.092*Price-0.044*Age-0.14*I(Urban=Yes)-0.076*I(US=Yes)
$$

Let's look at a case where a point would be in a rural area outside of the US

$$
Sales=7.20+0.094*CompPrice+0.013*Income+0.13*Advertising-0.0001*Population-0.092*Price-0.044*Age
$$

In the rural United States
$$
Sales=7.20+0.094*CompPrice+0.013*Income+0.13*Advertising-0.0001*Population-0.092*Price-0.044*Age-0.076*1\\
Sales=7.124+0.094*CompPrice+0.013*Income+0.13*Advertising-0.0001*Population-0.092*Price-0.044*Age
$$
In the Urban US
$$
Sales=7.20+0.094*CompPrice+0.013*Income+0.13*Advertising-0.0001*Population-0.092*Price-0.044*Age-0.14*1-0.076*1\\
Sales=6.984+0.094*CompPrice+0.013*Income+0.13*Advertising-0.0001*Population-0.092*Price-0.044*Age
$$
```{r}
summary(m1)
anova(m1)
```

```{r}
m2<-lm(Sales~CompPrice+Income+Advertising+Population+Price+Age+Urban+US+ShelveLoc,data=Carseats)
par(mfrow=c(2,2))
plot(m2)

summary(m2)
anova(m2)
```


```{r}
m3<-lm(Sales~CompPrice+Income+Advertising+Price+Age+ShelveLoc,data=Carseats)
par(mfrow=c(2,2))
plot(m3)
anova(m2,m3)

summary(m3)
```

```{r}
m4<-lm(Sales~CompPrice+Income+Advertising+Price+Age+ShelveLoc+ShelveLoc*US+ShelveLoc*Urban,data=Carseats)
par(mfrow=c(2,2))
plot(m4)
summary(m4)
anova(m4)
anova(m3,m4)
summary(m3)
```

```{r}
library(car)
library(effects)
effects(m3)
```
